package web.dao;

import web.entity.Rule;

import java.util.List;

public interface RuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Sat Sep 20 16:51:12 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Sat Sep 20 16:51:12 CST 2014
     */
    int insert(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Sat Sep 20 16:51:12 CST 2014
     */
    int insertSelective(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Sat Sep 20 16:51:12 CST 2014
     */
    Rule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Sat Sep 20 16:51:12 CST 2014
     */
    int updateByPrimaryKeySelective(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Sat Sep 20 16:51:12 CST 2014
     */
    int updateByPrimaryKey(Rule record);

    /**
     * 获取所有规则
     * @return
     */
    List<Rule> selectList(Rule rule);

    /**
     * 获取总数
     * @param rule
     * @return
     */
    Integer selectCount(Rule rule);
}